// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    
    
    [UnityEditor.InitializeOnLoadAttribute()]
    [uFrame.Attributes.uFrameIdentifier("6e2f1df2-0195-414d-97d8-55c45c9b2461")]
    public class PlayfabEditorExtensions {
        
        [UnityEditor.MenuItem("GameObject/Create Playfab Kernel", false, 0)]
        public static void AddKernel() {
            Invert.uFrame.ECS.Templates.EcsEditorExtensionTemplate.AddEcsKernelWith<Playfab.PlayfabLoader>();
        }
    }
}
