// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    public partial class PlayfabLoader : uFrame.Kernel.SystemLoader {
        
        public override void Load() {
            EcsSystem system = null;
            system = this.AddSystem<PlayFabPlayerStatsSystem>();
            system = this.AddSystem<PlayerDataSystem>();
            system = this.AddSystem<SettingsSystem>();
            system = this.AddSystem<NotificationSystem>();
            system = this.AddSystem<PlayerStatsSystem>();
            system = this.AddSystem<PlayfabTitleDataSystem>();
            system = this.AddSystem<PlayFabPlayerDataSystem>();
            system = this.AddSystem<DemoPlayerSystem>();
            system = this.AddSystem<LoginSystem>();
            system = this.AddSystem<LoginUISystem>();
            system = this.AddSystem<PlayfabLoginSystem>();
            system = this.AddSystem<GameSystem>();
            system = this.AddSystem<ScenesSystem>();
            system = this.AddSystem<NotificationsUISystem>();
        }
    }
}
