// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    using PlayFab.ClientModels;
    using PlayFab;
    
    
    public class PlayfabLoginSystemLoginUserHandler {
        
        private Playfab.LoginUser _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private PlayFab.ClientModels.LoginWithEmailAddressRequest CreateObject14_Result = default( PlayFab.ClientModels.LoginWithEmailAddressRequest );
        
        private PlayFab.ClientModels.LoginWithEmailAddressRequest ActionNode13_request = default( PlayFab.ClientModels.LoginWithEmailAddressRequest );
        
        private object ActionNode13_customData = default( System.Object );
        
        private PlayFab.ClientModels.LoginResult ActionNode13_result = default( PlayFab.ClientModels.LoginResult );
        
        private PlayFab.PlayFabError ActionNode13_error = default( PlayFab.PlayFabError );
        
        private Playfab.UserLoggedIn PublishEventNode15_Result = default( Playfab.UserLoggedIn );
        
        private object ActionNode18_message = default( System.Object );
        
        public Playfab.LoginUser Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // CreateObject
            var CreateObject14_Object = new LoginWithEmailAddressRequest();
            CreateObject14_Object.TitleId = PlayfabLoginSystem.Instance.TitleId;
            CreateObject14_Object.Email = Event.Email;
            CreateObject14_Object.Password = Event.Password;
            CreateObject14_Result = CreateObject14_Object;
            ActionNode13_request = CreateObject14_Result;
            // ActionNode
            // Visit PlayFab.PlayFabClientAPI.LoginWithEmailAddress
            PlayFab.PlayFabClientAPI.LoginWithEmailAddress(ActionNode13_request, ActionNode13_resultCallback, ActionNode13_errorCallback, ActionNode13_customData);
        }
        
        private void ActionNode13_resultCallback(PlayFab.ClientModels.LoginResult result) {
            ActionNode13_result = result;
            // PublishEventNode
            var PublishEventNode15_Event = new UserLoggedIn();
            System.Publish(PublishEventNode15_Event);
            PublishEventNode15_Result = PublishEventNode15_Event;
        }
        
        private void ActionNode13_errorCallback(PlayFab.PlayFabError error) {
            ActionNode13_error = error;
            ActionNode18_message = ActionNode13_error.ErrorMessage;
            // ActionNode
            // Visit uFrame.Actions.DebugLibrary.LogMessage
            uFrame.Actions.DebugLibrary.LogMessage(ActionNode18_message);
        }
    }
}
