// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class PlayerDataSystemUserLoggedInHandler {
        
        private Playfab.UserLoggedIn _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private Playfab.LoadData PublishEventNode16_Result = default( Playfab.LoadData );
        
        public Playfab.UserLoggedIn Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // PublishEventNode
            var PublishEventNode16_Event = new LoadData();
            System.Publish(PublishEventNode16_Event);
            PublishEventNode16_Result = PublishEventNode16_Event;
        }
    }
}
