// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    using UnityEngine;
    
    
    public class ScenesSystemLoadMenuSceneHandler {
        
        private Playfab.LoadMenuScene _Event;
        
        private uFrame.ECS.EcsSystem _System;
        
        private int ActionNode12_index = default( System.Int32 );
        
        private UnityEngine.AsyncOperation ActionNode12_Result = default( UnityEngine.AsyncOperation );
        
        public Playfab.LoadMenuScene Event {
            get {
                return _Event;
            }
            set {
                _Event = value;
            }
        }
        
        public uFrame.ECS.EcsSystem System {
            get {
                return _System;
            }
            set {
                _System = value;
            }
        }
        
        public virtual void Execute() {
            // ActionNode
            // Visit UnityEngine.Application.LoadLevelAdditiveAsync
            ActionNode12_Result = UnityEngine.Application.LoadLevelAdditiveAsync(ActionNode12_index);
        }
    }
}
