// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UniRx;
    using uFrame.ECS;
    
    
    public partial class NotificationSystemBase : uFrame.ECS.EcsSystem {
        
        public override void Setup() {
            base.Setup();
            this.OnEvent<Playfab.NotificationMessage>().Subscribe(_=>{ LogDebugMessageFilter(_); }).DisposeWith(this);
        }
        
        protected virtual void LogDebugMessageHandler(Playfab.NotificationMessage data) {
            var handler = new LogDebugMessageHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void LogDebugMessageFilter(Playfab.NotificationMessage data) {
            this.LogDebugMessageHandler(data);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("3121d596-0f19-44fe-b228-ce7fa279b1ca")]
    public partial class NotificationSystem : NotificationSystemBase {
        
        private static NotificationSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private Boolean _DebugLog;
        
        public NotificationSystem() {
            Instance = this;
        }
        
        public static NotificationSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public Boolean DebugLog {
            get {
                return _DebugLog;
            }
            set {
                _DebugLog = value;
            }
        }
    }
}
