// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using UniRx;
    using uFrame.ECS;
    
    
    public partial class PlayerStatsSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<IPlayerStat> _PlayerStatManager;
        
        public IEcsComponentManagerOf<IPlayerStat> PlayerStatManager {
            get {
                return _PlayerStatManager;
            }
            set {
                _PlayerStatManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            PlayerStatManager = ComponentSystem.RegisterGroup<PlayerStatGroup,IPlayerStat>();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("342a0f51-82ab-496f-8631-d3c92156fd18")]
    public partial class PlayerStatsSystem : PlayerStatsSystemBase {
        
        private static PlayerStatsSystem _Instance;
        
        public PlayerStatsSystem() {
            Instance = this;
        }
        
        public static PlayerStatsSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
