// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using uFrame.ECS;
    using UniRx;
    
    
    public partial class PlayerDataSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<ICloudData> _CloudDataManager;
        
        public IEcsComponentManagerOf<ICloudData> CloudDataManager {
            get {
                return _CloudDataManager;
            }
            set {
                _CloudDataManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            CloudDataManager = ComponentSystem.RegisterGroup<CloudDataGroup,ICloudData>();
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("1e01b02e-90fd-4870-a162-ac33b4fc8587")]
    public partial class PlayerDataSystem : PlayerDataSystemBase {
        
        private static PlayerDataSystem _Instance;
        
        public PlayerDataSystem() {
            Instance = this;
        }
        
        public static PlayerDataSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
    }
}
