// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.Kernel;
    using Playfab;
    using UniRx;
    using uFrame.ECS;
    
    
    public partial class ScenesSystemBase : uFrame.ECS.EcsSystem {
        
        private IEcsComponentManagerOf<MenuScene> _MenuSceneManager;
        
        private IEcsComponentManagerOf<GameScene> _GameSceneManager;
        
        private IEcsComponentManagerOf<LoginScene> _LoginSceneManager;
        
        public IEcsComponentManagerOf<MenuScene> MenuSceneManager {
            get {
                return _MenuSceneManager;
            }
            set {
                _MenuSceneManager = value;
            }
        }
        
        public IEcsComponentManagerOf<GameScene> GameSceneManager {
            get {
                return _GameSceneManager;
            }
            set {
                _GameSceneManager = value;
            }
        }
        
        public IEcsComponentManagerOf<LoginScene> LoginSceneManager {
            get {
                return _LoginSceneManager;
            }
            set {
                _LoginSceneManager = value;
            }
        }
        
        public override void Setup() {
            base.Setup();
            MenuSceneManager = ComponentSystem.RegisterComponent<MenuScene>(16);
            GameSceneManager = ComponentSystem.RegisterComponent<GameScene>(14);
            LoginSceneManager = ComponentSystem.RegisterComponent<LoginScene>(15);
            this.OnEvent<Playfab.LoadGameScene>().Subscribe(_=>{ ScenesSystemLoadGameSceneFilter(_); }).DisposeWith(this);
            LoginSceneManager.CreatedObservable.Subscribe(LoginSceneCreatedFilter).DisposeWith(this);
            this.OnEvent<Playfab.LoadLoginScene>().Subscribe(_=>{ ScenesSystemLoadLoginSceneFilter(_); }).DisposeWith(this);
            GameSceneManager.CreatedObservable.Subscribe(GameSceneCreatedFilter).DisposeWith(this);
            this.OnEvent<Playfab.LoadMenuScene>().Subscribe(_=>{ ScenesSystemLoadMenuSceneFilter(_); }).DisposeWith(this);
            MenuSceneManager.CreatedObservable.Subscribe(MenuSceneCreatedFilter).DisposeWith(this);
        }
        
        protected virtual void ScenesSystemLoadGameSceneHandler(Playfab.LoadGameScene data) {
            var handler = new ScenesSystemLoadGameSceneHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void ScenesSystemLoadGameSceneFilter(Playfab.LoadGameScene data) {
            this.ScenesSystemLoadGameSceneHandler(data);
        }
        
        protected virtual void LoginSceneCreated(LoginScene data, LoginScene group) {
            var handler = new LoginSceneCreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void LoginSceneCreatedFilter(LoginScene data) {
            var GroupLoginScene = LoginSceneManager[data.EntityId];
            if (GroupLoginScene == null) {
                return;
            }
            if (!GroupLoginScene.Enabled) {
                return;
            }
            this.LoginSceneCreated(data, GroupLoginScene);
        }
        
        protected virtual void ScenesSystemLoadLoginSceneHandler(Playfab.LoadLoginScene data) {
            var handler = new ScenesSystemLoadLoginSceneHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void ScenesSystemLoadLoginSceneFilter(Playfab.LoadLoginScene data) {
            this.ScenesSystemLoadLoginSceneHandler(data);
        }
        
        protected virtual void GameSceneCreated(GameScene data, GameScene group) {
            var handler = new GameSceneCreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void GameSceneCreatedFilter(GameScene data) {
            var GroupGameScene = GameSceneManager[data.EntityId];
            if (GroupGameScene == null) {
                return;
            }
            if (!GroupGameScene.Enabled) {
                return;
            }
            this.GameSceneCreated(data, GroupGameScene);
        }
        
        protected virtual void ScenesSystemLoadMenuSceneHandler(Playfab.LoadMenuScene data) {
            var handler = new ScenesSystemLoadMenuSceneHandler();
            handler.System = this;
            handler.Event = data;
            handler.Execute();
        }
        
        protected void ScenesSystemLoadMenuSceneFilter(Playfab.LoadMenuScene data) {
            this.ScenesSystemLoadMenuSceneHandler(data);
        }
        
        protected virtual void MenuSceneCreated(MenuScene data, MenuScene group) {
            var handler = new MenuSceneCreated();
            handler.System = this;
            handler.Event = data;
            handler.Group = group;
            handler.Execute();
        }
        
        protected void MenuSceneCreatedFilter(MenuScene data) {
            var GroupMenuScene = MenuSceneManager[data.EntityId];
            if (GroupMenuScene == null) {
                return;
            }
            if (!GroupMenuScene.Enabled) {
                return;
            }
            this.MenuSceneCreated(data, GroupMenuScene);
        }
    }
    
    [uFrame.Attributes.uFrameIdentifier("e9a5599a-8af2-4447-b107-3bc68e210b9f")]
    public partial class ScenesSystem : ScenesSystemBase {
        
        private static ScenesSystem _Instance;
        
        [UnityEngine.SerializeField()]
        private String _MenuSceneName;
        
        [UnityEngine.SerializeField()]
        private String _LoginSceneName;
        
        [UnityEngine.SerializeField()]
        private String _GameSceneName;
        
        public ScenesSystem() {
            Instance = this;
        }
        
        public static ScenesSystem Instance {
            get {
                return _Instance;
            }
            set {
                _Instance = value;
            }
        }
        
        public String MenuSceneName {
            get {
                return _MenuSceneName;
            }
            set {
                _MenuSceneName = value;
            }
        }
        
        public String LoginSceneName {
            get {
                return _LoginSceneName;
            }
            set {
                _LoginSceneName = value;
            }
        }
        
        public String GameSceneName {
            get {
                return _GameSceneName;
            }
            set {
                _GameSceneName = value;
            }
        }
    }
}
