// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UniRx;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.EventId(2)]
    public partial class LoginUser : object {
        
        [UnityEngine.SerializeField()]
        private String _Email;
        
        [UnityEngine.SerializeField()]
        private String _Password;
        
        public String Email {
            get {
                return _Email;
            }
            set {
                _Email = value;
            }
        }
        
        public String Password {
            get {
                return _Password;
            }
            set {
                _Password = value;
            }
        }
    }
}
