// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using uFrame.Kernel;
    
    
    [uFrame.Attributes.uFrameIdentifier("e14ba008-3cff-48f1-8b64-07f0944904e4")]
    public partial interface IPlayerStat : uFrame.ECS.IEcsComponent {
        
        System.Reflection.PropertyInfo[] PlayerStatMembers {
            get;
        }
    }
}
