// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using Invert.Json;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(14)]
    [uFrame.Attributes.uFrameIdentifier("e74039aa-6571-457d-b870-ba52a9d9af1d")]
    public partial class GameScene : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 14;
            }
        }
    }
}
