// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using Invert.Json;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(15)]
    [uFrame.Attributes.uFrameIdentifier("5c223b6f-d426-4968-94aa-2149705cfbd0")]
    public partial class LoginScene : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 15;
            }
        }
    }
}
