// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Playfab;
    using Invert.Json;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(2)]
    [uFrame.Attributes.uFrameIdentifier("57a70731-0a34-44cd-ba93-5da041c8679c")]
    public partial class LoginButton : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private LoginUI _LoginUI;
        
        private Subject<PropertyChangedEvent<LoginUI>> _LoginUIObservable;
        
        private PropertyChangedEvent<LoginUI> _LoginUIEvent;
        
        public override int ComponentId {
            get {
                return 2;
            }
        }
        
        public IObservable<PropertyChangedEvent<LoginUI>> LoginUIObservable {
            get {
                return _LoginUIObservable ?? (_LoginUIObservable = new Subject<PropertyChangedEvent<LoginUI>>());
            }
        }
        
        public LoginUI LoginUI {
            get {
                return _LoginUI;
            }
            set {
                SetLoginUI(value);
            }
        }
        
        public virtual void SetLoginUI(LoginUI value) {
            SetProperty(ref _LoginUI, value, ref _LoginUIEvent, _LoginUIObservable);
        }
    }
}
