// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using UniRx;
    using Invert.Json;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(16)]
    [uFrame.Attributes.uFrameIdentifier("5e14a09e-c5d0-45c9-b8fb-a80614821ffe")]
    public partial class MenuScene : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 16;
            }
        }
    }
}
