// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using UnityEngine.UI;
    using Invert.Json;
    using UniRx;
    using UnityEngine;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.ComponentId(20)]
    [uFrame.Attributes.uFrameIdentifier("9888f9eb-2a8a-46c6-96bd-b1ae2a5b1f1a")]
    public partial class NotificationUI : uFrame.ECS.EcsComponent {
        
        [UnityEngine.SerializeField()]
        private Text _TitleText;
        
        [UnityEngine.SerializeField()]
        private Text _MessageText;
        
        private Subject<PropertyChangedEvent<Text>> _TitleTextObservable;
        
        private PropertyChangedEvent<Text> _TitleTextEvent;
        
        private Subject<PropertyChangedEvent<Text>> _MessageTextObservable;
        
        private PropertyChangedEvent<Text> _MessageTextEvent;
        
        public override int ComponentId {
            get {
                return 20;
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> TitleTextObservable {
            get {
                return _TitleTextObservable ?? (_TitleTextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public IObservable<PropertyChangedEvent<Text>> MessageTextObservable {
            get {
                return _MessageTextObservable ?? (_MessageTextObservable = new Subject<PropertyChangedEvent<Text>>());
            }
        }
        
        public Text TitleText {
            get {
                return _TitleText;
            }
            set {
                SetTitleText(value);
            }
        }
        
        public Text MessageText {
            get {
                return _MessageText;
            }
            set {
                SetMessageText(value);
            }
        }
        
        public virtual void SetTitleText(Text value) {
            SetProperty(ref _TitleText, value, ref _TitleTextEvent, _TitleTextObservable);
        }
        
        public virtual void SetMessageText(Text value) {
            SetProperty(ref _MessageText, value, ref _MessageTextEvent, _MessageTextObservable);
        }
    }
}
