// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Json;
    using uFrame.ECS;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(19)]
    [uFrame.Attributes.uFrameIdentifier("ecdced36-e91e-4e2d-ab66-8224a77bfc64")]
    public partial class SaveGameButton : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 19;
            }
        }
    }
}
