// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using uFrame.ECS;
    using Invert.Json;
    using UniRx;
    using UnityEngine;
    
    
    [uFrame.Attributes.ComponentId(6)]
    [uFrame.Attributes.uFrameIdentifier("7c648a21-8a16-4733-842e-d4c9fa5a9d49")]
    public partial class VisibleWhenAuthenticated : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 6;
            }
        }
    }
}
