// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Playfab {
    using System;
    using System.Collections;
    using System.Collections.Generic;
    using System.Linq;
    using Invert.Json;
    using UniRx;
    using UnityEngine;
    using uFrame.ECS;
    
    
    [uFrame.Attributes.ComponentId(7)]
    [uFrame.Attributes.uFrameIdentifier("950087a8-658c-4817-85a1-20cfaf2fd5d3")]
    public partial class VisibleWhenNotAuthenticated : uFrame.ECS.EcsComponent {
        
        public override int ComponentId {
            get {
                return 7;
            }
        }
    }
}
